### ISSUE TITLE
Unable to use single namespace

### ISSUE THREAD

**Issue by letmaik** [esdoc/esdoc-importpath-plugin#5]
I organize my library into subfolders but the outer API groups all of it into a single module which is the main package. This means I want all my documented imports look like  `import {...} from 'package'`. But this seems impossible as this plugin always adds a slash, so it becoms `'package/'`. Any way to support this common way?

**Comment by h13i32maru** [comment]
Please tell me minimum repository that reproduces this issue.
I re-open this when I get your reply.
